"""
功能概述
`wqb_core.foundation.urls` 模块。

这个文件提供与当前文件名对应的具体实现。

主推荐入口
- 以本模块中定义的公开类、函数和常量为准。

适用场景
- 作为库模块被导入使用。

注意事项
- 本文件中的中文说明已按 UTF-8 重写。
- 具体参数、返回值和示例以函数签名与方法 docstring 为准。
"""

__all__ = [
    'HTTP_API_WORLDQUANTBRAIN_COM',
    'HTTPS_API_WORLDQUANTBRAIN_COM',
    'WQB_API_URL',
    'URL_ALPHAS',
    'URL_ALPHAS_ALPHAID',
    'URL_ALPHAS_ALPHAID_CHECK',
    'URL_ALPHAS_ALPHAID_SUBMIT',
    'URL_AUTHENTICATION',
    'URL_DATACATEGORIES',
    'URL_DATAFIELDS',
    'URL_DATAFIELDS_FIELDID',
    'URL_DATASETS',
    'URL_DATASETS_DATASETID',
    'URL_OPERATORS',
    'URL_SIMULATIONS',
    'URL_USERS',
    'URL_USERS_SELF',
    'URL_USERS_SELF_ALPHAS',
    'URL_USERS_SELF_ACTIVITIES_PYRAMID_MULTIPLIERS',
    'URL_USERS_SELF_ACTIVITIES_PYRAMID_ALPHAS',
    'URL_USERS_SELF_PYRAMID_ALPHAS',
    'URL_ACTIVITIES_PYRAMID_ALPHAS',
    'URL_EVENTS',
    'URL_CONSULTANT_BOARDS_LEADER',
    'URL_SIMULATIONS_SUPER_SELECTION',
    'URL_USERS_USERID',
    'URL_TUTORIALS',
    'URL_TUTORIAL_PAGES_PAGEID',
    'URL_USERS_SELF_MESSAGES',
    'URL_USERS_USERID_ACTIVITIES',
    'URL_USERS_USERID_COMPETITIONS',
    'URL_COMPETITIONS',
    'URL_COMPETITIONS_COMPETITIONID',
    'URL_COMPETITIONS_COMPETITIONID_AGREEMENT',
    'URL_ALPHAS_ALPHAID_PERFORMANCE_COMPARISON',
    'URL_ALPHAS_ALPHAID_CORRELATION',
    'URL_ALPHAS_ALPHAID_CORRELATION_SELF',
    'URL_ALPHAS_ALPHAID_CORRELATION_PROD',
    'URL_ALPHAS_ALPHAID_CORRELATION_POWERPOOL',
    'URL_USERS_SELF_ALPHAS_ALPHAID',
    'URL_USERS_SELF_ALPHAS_ALPHAID_BEFORE_AFTER_PERFORMANCE',
    'URL_ALPHAS_ALPHAID_RECORDSETS',
    'URL_ALPHAS_ALPHAID_RECORDSETS_YEARLYSTATS',
    'URL_ALPHAS_ALPHAID_RECORDSETS_PNL',
    'URL_ALPHAS_ALPHAID_RECORDSETS_SHARPE',
]

HTTP_API_WORLDQUANTBRAIN_COM = 'http://api.worldquantbrain.com'
HTTPS_API_WORLDQUANTBRAIN_COM = 'https://api.worldquantbrain.com'

WQB_API_URL = HTTPS_API_WORLDQUANTBRAIN_COM
URL_ALPHAS = WQB_API_URL + '/alphas'
URL_ALPHAS_ALPHAID = URL_ALPHAS + '/{}'
URL_ALPHAS_ALPHAID_CHECK = URL_ALPHAS_ALPHAID + '/check'
URL_ALPHAS_ALPHAID_SUBMIT = 'http://api.worldquantbrain.com:443/alphas/{}/submit'
URL_AUTHENTICATION = WQB_API_URL + '/authentication'
URL_DATACATEGORIES = WQB_API_URL + '/data-categories'
URL_DATAFIELDS = WQB_API_URL + '/data-fields'
URL_DATAFIELDS_FIELDID = URL_DATAFIELDS + '/{}'
URL_DATASETS = WQB_API_URL + '/data-sets'
URL_DATASETS_DATASETID = URL_DATASETS + '/{}'
URL_OPERATORS = WQB_API_URL + '/operators'
URL_SIMULATIONS = WQB_API_URL + '/simulations'
URL_USERS = WQB_API_URL + '/users'
URL_USERS_SELF = URL_USERS + '/self'
URL_USERS_SELF_ALPHAS = URL_USERS_SELF + '/alphas'
URL_USERS_USERID = URL_USERS + '/{}'
URL_USERS_SELF_ACTIVITIES_PYRAMID_MULTIPLIERS = (
    URL_USERS_SELF + '/activities/pyramid-multipliers'
)
URL_USERS_SELF_ACTIVITIES_PYRAMID_ALPHAS = (
    URL_USERS_SELF + '/activities/pyramid-alphas'
)
URL_USERS_SELF_PYRAMID_ALPHAS = URL_USERS_SELF + '/pyramid/alphas'
URL_ACTIVITIES_PYRAMID_ALPHAS = WQB_API_URL + '/activities/pyramid-alphas'
URL_EVENTS = WQB_API_URL + '/events'
URL_CONSULTANT_BOARDS_LEADER = WQB_API_URL + '/consultant/boards/leader'
URL_SIMULATIONS_SUPER_SELECTION = URL_SIMULATIONS + '/super-selection'
URL_TUTORIALS = WQB_API_URL + '/tutorials'
URL_TUTORIAL_PAGES_PAGEID = WQB_API_URL + '/tutorial-pages/{}'
URL_USERS_SELF_MESSAGES = URL_USERS_SELF + '/messages'
URL_USERS_USERID_ACTIVITIES = URL_USERS + '/{}/activities'
URL_USERS_USERID_COMPETITIONS = URL_USERS + '/{}/competitions'
URL_COMPETITIONS = WQB_API_URL + '/competitions'
URL_COMPETITIONS_COMPETITIONID = URL_COMPETITIONS + '/{}'
URL_COMPETITIONS_COMPETITIONID_AGREEMENT = URL_COMPETITIONS_COMPETITIONID + '/agreement'
URL_ALPHAS_ALPHAID_PERFORMANCE_COMPARISON = URL_ALPHAS_ALPHAID + '/performance-comparison'
URL_ALPHAS_ALPHAID_CORRELATION = URL_ALPHAS_ALPHAID + '/correlations'
URL_ALPHAS_ALPHAID_CORRELATION_SELF = URL_ALPHAS_ALPHAID_CORRELATION + '/self'
URL_ALPHAS_ALPHAID_CORRELATION_PROD = URL_ALPHAS_ALPHAID_CORRELATION + '/prod'
URL_ALPHAS_ALPHAID_CORRELATION_POWERPOOL = URL_ALPHAS_ALPHAID_CORRELATION + '/power-pool'
URL_USERS_SELF_ALPHAS_ALPHAID = URL_USERS_SELF_ALPHAS + '/{}'
URL_USERS_SELF_ALPHAS_ALPHAID_BEFORE_AFTER_PERFORMANCE = (
    URL_USERS_SELF_ALPHAS_ALPHAID + '/before-and-after-performance'
)
URL_ALPHAS_ALPHAID_RECORDSETS = URL_ALPHAS_ALPHAID + '/recordsets'
URL_ALPHAS_ALPHAID_RECORDSETS_YEARLYSTATS = URL_ALPHAS_ALPHAID_RECORDSETS + '/yearly-stats'
URL_ALPHAS_ALPHAID_RECORDSETS_PNL = URL_ALPHAS_ALPHAID_RECORDSETS + '/pnl'
URL_ALPHAS_ALPHAID_RECORDSETS_SHARPE = URL_ALPHAS_ALPHAID_RECORDSETS + '/sharpe'
